apiVersion: v1
kind: Service
metadata:
  name: {{ .Chart.Name }}-postgres
  namespace: pathfinder
  labels:
    app: {{ .Chart.Name }}-postgres
spec:
  type: NodePort
  ports:
   - port: 5432
     nodePort: 30007
  selector:
   app: {{ .Chart.Name }}-postgres