apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pathfinder
  name: {{ .Chart.Name }}-postgres
spec:
  selector: 
    matchLabels:
      app: {{ .Chart.Name }}-postgres
  replicas: 1
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-postgres
    spec:
      containers:
      - name: {{ .Chart.Name }}-postgres
        image: postgres:10.4
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: 128Mi
            cpu: 0.1m
          limits:
            memory: 256Mi
            cpu: 0.25m
        env:
        - name: POSTGRES_DB
          value: database_pathfiner_official
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: database-pathfinder-official-secret
              key: password
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: database-pathfinder-official-secret
              key: user
