{{ if .Values.deployment.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}
  namespace: pathfinder
  labels: 
    apps: {{ .Chart.Name }}
    release: {{ .Chart.Name }}
spec:
  selector: 
    matchLabels:
      app: {{ .Chart.Name }}
  replicas: 1
  template:
    metadata:
      name: {{ .Chart.Name }}
      labels:
        app: {{ .Chart.Name }}
      annotations:
        valuesChecksum: {{ .Values | toYaml | sha256sum | trunc 63 }}
    spec:
      imagePullSecrets:
      - name: artifactory-credentials
      containers:
      
        #POSTGRESS
      - name: {{ .Chart.Name }}-postgres
        image: postgres:13.2-alpine
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: 128Mi
            cpu: 0.1m
          limits:
            memory: 2048Mi
            cpu: 2m
        env:
        - name: POSTGRES_DB
          value: {{.Values.deployment.appsettings.databases.official.database}}
        - name: POSTGRES_PASSWORD
          value: {{.Values.deployment.appsettings.databases.official.password}}
        - name: POSTGRES_USER
          value: {{.Values.deployment.appsettings.databases.official.userId}}
        readinessProbe:
          exec:
            command: ["pg_isready", "-U", {{.Values.deployment.appsettings.databases.official.userId | quote}}]
          timeoutSeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          exec:
            command: ["pg_isready", "-U", {{.Values.deployment.appsettings.databases.official.userId | quote}}]
          timeoutSeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        startupProbe:
          exec:
            command: ["pg_isready"]
          timeoutSeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 50

        #DOTNET
      - name: {{ .Chart.Name }}
        image: silvester.jfrog.io/silvester-docker/pathfinder-official-api:{{ .Values.version }}
        imagePullPolicy: Always

        {{ if .Values.deployment.probes.liveness.enabled }}
        livenessProbe:
          initialDelaySeconds: {{ .Values.deployment.probes.liveness.initialDelaySeconds }}
          periodSeconds: {{ .Values.deployment.probes.liveness.periodSeconds }}
          timeoutSeconds: {{ .Values.deployment.probes.liveness.timeoutSeconds }}
          successThreshold: {{ .Values.deployment.probes.liveness.successThreshold }}
          failureThreshold: {{ .Values.deployment.probes.liveness.failureThreshold }}
          httpGet: 
            path: /probes/liveness
            port: 80
        {{- end }}
        
        {{ if .Values.deployment.probes.readiness.enabled }}
        readinessProbe:
          initialDelaySeconds: {{ .Values.deployment.probes.readiness.initialDelaySeconds }}
          periodSeconds: {{ .Values.deployment.probes.readiness.periodSeconds }}
          timeoutSeconds: {{ .Values.deployment.probes.readiness.timeoutSeconds }}
          successThreshold: {{ .Values.deployment.probes.readiness.successThreshold }}
          failureThreshold: {{ .Values.deployment.probes.readiness.failureThreshold }}
          httpGet: 
            path: /probes/readiness
            port: 80
        {{- end }}
        
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
          
        resources:
          requests:
            memory: 256Mi
            cpu: 0.5m
          limits:
            memory: 256Mi
            cpu: 1

        volumeMounts:
        {{- if .Values.deployment.appsettings }}
        - name: appsettings-volume
          mountPath: /app/appsettings.json
          subPath: appsettings.json
        {{- end }}        
      volumes: 
      {{ if .Values.deployment.appsettings }}
      - name: appsettings-volume
        configMap:
          name: {{ .Chart.Name }}-configmap-appsettings
          defaultMode: 0777
      {{ end }}
{{ end }}    
    