apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pathfinder
  name: {{ .Chart.Name }}-postgres
spec:
  selector: 
    matchLabels:
      app: {{ .Chart.Name }}-postgres
  replicas: 1
  template:
    metadata:
      annotations:
        checksum/version: {{ .Values.version }}
      labels:
        app: {{ .Chart.Name }}-postgres
    spec:
      containers:
      - name: {{ .Chart.Name }}-postgres
        image: postgres:13.2-alpine
        imagePullPolicy: "Always"
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: 128Mi
            cpu: 0.1m
          limits:
            memory: 2048Mi
            cpu: 2m
        env:
        - name: POSTGRES_DB
          value: database_pathfinder_official
        - name: POSTGRES_PASSWORD
          value: password
        - name: POSTGRES_USER
          value: user
        readinessProbe:
          exec:
            command: ["pg_isready"]
          timeoutSeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          exec:
            command: ["pg_isready"]
          initialDelaySeconds: 300
          timeoutSeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 10
        startupProbe:
          exec:
            command: ["pg_isready"]
          timeoutSeconds: 30
          periodSeconds: 10
          successThreshold: 1
          failureThreshold: 30
