deployment:
  enabled: true
  appsettings:
    logging: 
      includeScopes: true
      logLevel:
        default: Information
        system: Information
        microsoft: Information 
    databases:
      official:
        enabled: true
        server: localhost
        port: 5432
        database: database_pathfinder_official
        password: password
        userId: postgres
        timeout: 15
        commandTimeout: 20
        
  probes:
    liveness:
      enabled: false
      initialDelaySeconds: 60
      periodSeconds: 30
      timeoutSeconds: 10
      successThreshold: 1
      failureThreshold: 5
      
    readiness:
      enabled: true
      initialDelaySeconds: 0
      periodSeconds: 5
      timeoutSeconds: 10
      successThreshold: 1
      failureThreshold: 5
      
ingress:
  sslTermination: true